export const STRINGS = {
  app: {
    name: 'CareNest',
    tagline: 'Calm care, simplified.',
  },
  auth: {
    loginTitle: 'Welcome to CareNest',
    loginSubtitle: 'A calm place to organize care for someone you love.',
    signInGoogle: 'Continue with Google',
    signInApple: 'Continue with Apple',
    appleComingSoon: 'Coming soon',
    signOut: 'Sign Out',
    devNotice: 'Development mode — not for real health information.',
  },
  welcome: {
    title: 'You are in the right place',
    subtitle: 'CareNest helps you keep care details organized, so you can focus on what matters.',
    benefit1: 'Simple notes for daily care',
    benefit2: 'Everything in one calm place',
    benefit3: 'Built for family caregivers',
    continue: 'Continue',
  },
  onboarding: {
    back: 'Back',
    continue: 'Continue',
    complete: 'Complete Setup',
    stepWelcome: 'Welcome',
    stepRecipient: 'Care Recipient',
    stepCaregiver: 'You',
    stepDone: 'Done',
  },
  careRecipient: {
    title: 'Who are you caring for?',
    subtitle: 'Tell us a little about your loved one.',
    firstName: 'First Name',
    lastName: 'Last Name',
    dateOfBirth: 'Date of Birth',
    gender: 'Gender',
    healthDescription: 'Health Description',
    healthPlaceholder: 'Example: Mild dementia, takes Metformin daily, needs help with mobility.',
    voicePlaceholder: 'Voice input coming soon',
    hipaaTitle: 'Your privacy matters',
    hipaaText:
      'Your information is kept private and secure. CareNest is designed to help you organize care — not to replace medical advice.',
  },
  caregiver: {
    title: 'Tell us about you',
    subtitle: 'You are doing something important.',
    firstName: 'First Name',
    lastName: 'Last Name',
    dateOfBirth: 'Date of Birth',
    gender: 'Gender',
    encouragement: 'You are making a difference every day. CareNest is here to support you.',
  },
  dashboard: {
    title: 'Dashboard',
    greeting: 'Good morning',
    greetingAfternoon: 'Good afternoon',
    greetingEvening: 'Good evening',
    quickNote: 'Quick Note',
    quickNoteDesc: 'Jot down something important',
    recentActivity: 'Recent Activity',
    careSummary: 'Care Summary',
    emptyTitle: 'Your care journey starts here',
    emptyDesc: 'Create your first note to begin.',
  },
  notes: {
    title: 'Notes',
    newNote: 'New Note',
    search: 'Search notes...',
    filterAll: 'All',
    filterManual: 'Manual',
    filterVoice: 'Voice',
    voiceComingSoon: 'Voice notes coming soon',
    emptyTitle: 'No notes yet',
    emptyDesc: 'Tap New Note to record something about today.',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
  },
  nav: {
    dashboard: 'Home',
    notes: 'Notes',
    profile: 'Profile',
  },
  profile: {
    title: 'Profile',
    intro: 'Manage the details you added during setup.',
    name: 'Name',
    careRecipientSection: 'Care Recipient',
    caregiverSection: 'You',
    aboutSection: 'About',
    privacy: 'Privacy',
    privacyValue: 'Your data stays on this device',
    version: 'Version',
    age: 'Age',
    gender: 'Gender',
    health: 'Health notes',
    notSet: 'Not set',
    signOut: 'Sign Out',
  },
  errors: {
    generic: 'Something went wrong. Please try again.',
    required: 'This field is required',
    invalidDate: 'Please enter a valid date',
    notFound: 'Page not found',
    notFoundDesc: 'The page you are looking for does not exist.',
    goHome: 'Go Home',
    retry: 'Try Again',
  },
  gender: {
    male: 'Male',
    female: 'Female',
    other: 'Other',
    preferNotToSay: 'Prefer not to say',
  },
};
