export const STRINGS = {
  app: {
    name: 'CareNest',
    tagline: 'Calm care, simplified.',
  },
  auth: {
    loginTitle: 'Welcome to CareNest',
    loginSubtitle: 'A calm place to organize care for someone you love.',
    signInGoogle: 'Continue with Google',
    signInApple: 'Continue with Apple',
    appleComingSoon: 'Coming soon',
    signOut: 'Sign Out',
    orDivider: 'or',
    email: 'Email',
    emailPlaceholder: 'you@example.com',
    password: 'Password',
    passwordPlaceholder: 'Enter your password',
    login: 'Log In',
    loggingIn: 'Logging in…',
    forgotPassword: 'Forgot password?',
    noAccount: "Don't have an account?",
    createAccountLink: 'Create Account',
    // Create Account
    createTitle: 'Create your account',
    createSubtitle: 'Start organizing care in a few seconds.',
    firstName: 'First Name',
    lastName: 'Last Name',
    confirmPassword: 'Confirm Password',
    passwordHint: 'At least 8 characters, with a letter and a number.',
    createButton: 'Create Account',
    creating: 'Creating account…',
    haveAccount: 'Already have an account?',
    loginLink: 'Log In',
    verifyTitle: 'Check your email',
    verifyBody:
      'We sent a confirmation link to {email}. Open it to activate your account, then log in.',
    backToLogin: 'Back to Log In',
    // Forgot Password
    forgotTitle: 'Reset your password',
    forgotSubtitle: 'Enter your email and we will send you a reset link.',
    sendReset: 'Send Reset Link',
    sending: 'Sending…',
    forgotSentTitle: 'Check your email',
    forgotSentBody: 'If an account exists for {email}, a password reset link is on its way.',
    // Reset Password
    resetTitle: 'Set a new password',
    resetSubtitle: 'Choose a new password for your account.',
    newPassword: 'New Password',
    updatePassword: 'Update Password',
    updating: 'Updating…',
    resetDoneTitle: 'Password updated',
    resetDoneBody: 'Your password has been changed. You are all set.',
    continueToApp: 'Continue',
    resetInvalidTitle: 'Reset link expired',
    resetInvalidBody:
      'This password reset link is invalid or has expired. Request a new one to continue.',
    requestNewLink: 'Request a new link',
    resetChecking: 'Verifying your reset link…',
  },
  authErrors: {
    invalidEmail: 'Please enter a valid email address',
    passwordTooShort: 'Password must be at least 8 characters',
    passwordWeak: 'Password must include a letter and a number',
    passwordMismatch: 'Passwords do not match',
    signInFailed: 'Could not sign you in. Check your email and password.',
    signUpFailed: 'Could not create your account. Please try again.',
    resetFailed: 'Could not send the reset link. Please try again.',
    updateFailed: 'Could not update your password. Please try again.',
  },
  welcome: {
    title: 'You are in the right place',
    subtitle: 'CareNest helps you keep care details organized, so you can focus on what matters.',
    benefit1: 'Simple notes for daily care',
    benefit2: 'Everything in one calm place',
    benefit3: 'Built for family caregivers',
    continue: 'Continue',
  },
  onboarding: {
    back: 'Back',
    continue: 'Continue',
    complete: 'Complete Setup',
    stepWelcome: 'Welcome',
    stepRecipient: 'Care Recipient',
    stepCaregiver: 'You',
    stepDone: 'Done',
  },
  careRecipient: {
    title: 'Who are you caring for?',
    subtitle: 'Tell us a little about your loved one.',
    firstName: 'First Name',
    lastName: 'Last Name',
    dateOfBirth: 'Date of Birth',
    gender: 'Gender',
    healthDescription: 'Health Description',
    healthPlaceholder: 'Example: Mild dementia, takes Metformin daily, needs help with mobility.',
    voicePlaceholder: 'Voice input coming soon',
    hipaaTitle: 'Your privacy matters',
    hipaaText:
      'Your information is kept private and secure. CareNest is designed to help you organize care — not to replace medical advice.',
  },
  caregiver: {
    title: 'Tell us about you',
    subtitle: 'You are doing something important.',
    firstName: 'First Name',
    lastName: 'Last Name',
    dateOfBirth: 'Date of Birth',
    gender: 'Gender',
    encouragement: 'You are making a difference every day. CareNest is here to support you.',
  },
  dashboard: {
    title: 'Dashboard',
    greeting: 'Good morning',
    greetingAfternoon: 'Good afternoon',
    greetingEvening: 'Good evening',
    quickNote: 'Quick Note',
    quickNoteDesc: 'Jot down something important',
    recentActivity: 'Recent Activity',
    careSummary: 'Care Summary',
    emptyTitle: 'Your care journey starts here',
    emptyDesc: 'Create your first note to begin.',
  },
  notes: {
    title: 'Notes',
    newNote: 'New Note',
    search: 'Search notes...',
    filterAll: 'All',
    filterManual: 'Manual',
    filterVoice: 'Voice',
    voiceComingSoon: 'Voice notes coming soon',
    emptyTitle: 'No notes yet',
    emptyDesc: 'Tap New Note to record something about today.',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
  },
  nav: {
    dashboard: 'Home',
    notes: 'Notes',
    profile: 'Profile',
  },
  menu: {
    open: 'Account menu',
    profile: 'Profile',
    settings: 'Settings',
    signOut: 'Sign Out',
  },
  profile: {
    title: 'Profile',
    intro: 'Manage your account and the details you added during setup.',
    name: 'Name',
    email: 'Email',
    accountSection: 'Account',
    careRecipientSection: 'Care Recipient',
    caregiverSection: 'You',
    aboutSection: 'About',
    editProfile: 'Edit Profile',
    privacy: 'Privacy',
    privacyValue: 'Only you can see your data',
    version: 'Version',
    age: 'Age',
    gender: 'Gender',
    health: 'Health notes',
    notSet: 'Not set',
    signOut: 'Sign Out',
    editTitle: 'Edit profile',
    editSubtitle: 'Update the name on your account.',
    save: 'Save Changes',
    saving: 'Saving…',
    cancel: 'Cancel',
    saved: 'Profile updated',
  },
  errors: {
    generic: 'Something went wrong. Please try again.',
    required: 'This field is required',
    invalidDate: 'Please enter a valid date',
    notFound: 'Page not found',
    notFoundDesc: 'The page you are looking for does not exist.',
    goHome: 'Go Home',
    retry: 'Try Again',
  },
  gender: {
    male: 'Male',
    female: 'Female',
    other: 'Other',
    preferNotToSay: 'Prefer not to say',
  },
};
